name: Make calendar for Bislett Stadion
on:
    #schedule:
    #    - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    make-calendar:
        name: Make calendar
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Scrape website and make the calendar
              run: bun run src/calendar/make.ts

            - name: Move files to output folder
              run: mv

            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: .
                  clean: true
                  token: ${{ secrets.GITHUB_TOKEN }}
