name: Make calendar for Bislett Stadion
on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    make-calendar:
        name: Make calendar
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install
            - name: Scrape website and make the calendar
              run: bun script/index.ts
            - name: Upload output as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: calendar
                  path: bislett.ics
